[git_branch]
format = 'on [$symbol$branch]($style) '
symbol = 'ğŸŒ± '
style = 'green bold'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'red bold'

[github]
format = 'on [$symbol($username)]($style) '
symbol = 'ğŸ¦â€ğŸ”¥ '
style = 'purple bold'